<a href="https://colab.research.google.com/github/jangalasriramd7/MachineLearning/blob/main/Logistic_Regressor_on_Obesity_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# load and summarize the dataset
from pandas import read_csv
# load the dataset
dataset = read_csv('DB_Obesity.csv')
# summarize the dataset
dataset.describe()

# print the first 5 rows of data
dataset.head(5)

# count the number of nan values in each column
print(dataset.isnull().sum())

#removing rows that contain missing values
from numpy import nan
# summarize the shape of the raw data
print(dataset.shape)
# drop rows with missing values
dataset.dropna(inplace=True)
# summarize the shape of the data with missing rows removed
print(dataset.shape)

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in columns
dataset['Gender']= label_encoder.fit_transform(dataset['Gender'])
dataset['Age']= label_encoder.fit_transform(dataset['Age'])
dataset['Height']= label_encoder.fit_transform(dataset['Height'])
dataset['Weight']= label_encoder.fit_transform(dataset['Weight'])
dataset['family_history_with_overweight']= label_encoder.fit_transform(dataset['family_history_with_overweight'])
dataset['FAVC']= label_encoder.fit_transform(dataset['FAVC'])
dataset['FCVC']= label_encoder.fit_transform(dataset['FCVC'])
dataset['NCP']= label_encoder.fit_transform(dataset['NCP'])
dataset['CAEC']= label_encoder.fit_transform(dataset['CAEC'])
dataset['SMOKE']= label_encoder.fit_transform(dataset['SMOKE'])
dataset['CH2O']= label_encoder.fit_transform(dataset['CH2O'])
dataset['SCC']= label_encoder.fit_transform(dataset['SCC'])
dataset['FAF']= label_encoder.fit_transform(dataset['FAF'])
dataset['TUE']= label_encoder.fit_transform(dataset['TUE'])
dataset['CALC']= label_encoder.fit_transform(dataset['CALC'])
dataset['MTRANS']= label_encoder.fit_transform(dataset['MTRANS'])
dataset['NObeyesdad']= label_encoder.fit_transform(dataset['NObeyesdad'])

# print the first 5 rows of data
dataset.head(5)

x=dataset.iloc[:,0:16]
y=dataset.iloc[:,16]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score


acc =  accuracy_score(y_test, y_pred)

cm = confusion_matrix(y_test, y_pred)


print(acc)
print('confusion Matrix')
print(cm)

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
(2111, 17)
(2111, 17)
0.7777777777777778
confusion Matrix
[[66  0  0  0  0  0  0]
 [ 4 51  1  1  0  6  0]
 [ 0  0 46 12  5  0  6]
 [ 0  0  9 42  2  0  0]
 [ 0  0  0  0 54  0  0]
 [ 0  2  7  0  2 34 16]
 [ 0  1  6  2  0 12 36]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
